// ADDRESS
Table country {
    id varchar(36) [pk, note: "UUID for country, primary key"]
    country_name varchar(20) [not null, note: "name of the country"]
    country_code varchar(5) [note: "e.g: +237, +149"]
    flag varchar [note: "flag of the country, e.g: 🇨🇲, 🇧🇷, 🇬🇧, ..."]
    phone_regex varchar [note: "^(\+0?1\s)?\(?\d{3}\)?$, ..."]
    is_active boolean [default: true, note: "to enable or disable an instance"]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

Table address {
    id varchar(36) [pk, note: "UUID for address, primary key"]
    location_name varchar(60) [note: "e.g Ancienne Mairie Tsinga"]
    location_address varchar(255) [note: "'latitude,longitude' e.g `3.885306, 11.502750`, `3°53'07.1\"N 11°30'09.9\"E`"]
    neighborhood varchar(60) [note: "e.g Tsinga, Bankolo, Mendong, ..."]
    street varchar(60) [note: "e.g 345 Avenue Germaine, ..."]
    city varchar(60) [note: "Yaounde, Douala, ..."]
    region varchar(60) [note: "West, North, ..."]
    postal_code varchar(10) [note: "11 251"]
    country_id varchar(36) [ref: > country.id]
    is_active boolean [default: true, note: "to enable or disable an instance"]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

// AUTHENTICATION
Table user {
    id varchar(36) [pk, note: "UUID for user, primary key"]
    email varchar(36)
    phone varchar
    password varchar
    first_name varchar
    last_name varchar
    photo_profile varchar
    address_id varchar(36) [ref: > address.id]

    account_verification_code int [not null, note: "OPT code, e.g. 654790"]
    code_expiry timestamp [not null, note: "expire time"]
    account_verified boolean [default: false, note: "true if the user send the correct verification code before the expiry time"]

    enable_two_factor_auth boolean [default: false]

    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

Table two_factor_auth_session {
    session_id varchar(36) [pk, note: "UUID for user session"]
    user_id varchar(36) [ref: > user.id, not null, note: "user who tries to connect or who is connected"]
    ip_address varchar(255) [not null, note: "IP address of device which want to connect"]
    login_verification_code int [not null, note: "OPT code, e.g. 654790"]
    code_expiry timestamp [not null, note: "expire time of the OPT code"]
    login_verified boolean [default: false, note: "if the user is successfully logged"]
    session_expiry timestamp [default: null, note: "datetime when this session will expire"]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

// AUTHORIZATION
Table user_role {
    user_id varchar(36) [ref: > user.id, not null]
    role_id varchar(36) [ref: > role.id, not null]
    indexes {
        (user_id, role_id) [pk]
    }
}

Table role {
    id varchar(36) [pk, note: "UUID for role, primary key"]
    name varchar
    description text
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

Table role_permission {
    role_id varchar(36) [ref: > role.id, not null]
    permission_id varchar(36) [ref: > permission.id, not null]
    indexes {
        (role_id, permission_id) [pk]
    }
}

Table permission {
    id varchar(36) [pk, note: "UUID for permission, primary key"]
    name varchar
    description text
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

// EVENT ORGANIZER PROFILE
Table event_organizer {
    id varchar(36) [pk, note: "UUID for event organizer, primary key"]
    user_id varchar(36) [ref: > user.id, not null]

    business_name varchar(255) [not null]
    banner_image_url varchar(255)
    business_email varchar(100)
    business_phone varchar(20)
    business_website_url varchar(255)
    business_logo_url varchar(255)
    year_established int
    team_size int
    about text [note: "bio"]
    status enum('pending', 'approved', 'rejected', 'suspended') [default: 'pending']
    approval_notes text
    approved_by varchar(36) [ref: > user.id, default: null]
    approved_at timestamp

    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

Table event_organizer_validation_status {
    id varchar(36) [pk, note: "UUID for event organizer validation, primary key"]
    organizer_id varchar(36) [ref: > event_organizer.id, not null]
    status enum('pending', 'approved', 'rejected', 'suspended') [default: 'pending']
    validate_notes text [default: null, note: "comment of the user"]
    validate_by varchar(36) [ref: > user.id, not null, note: "reference of user who make validation"]
    validate_at timestamp [default: `now()`]
    indexes {
        (organizer_id, status) [unique]
    }
}

Table organizer_follower {
    organizer_id varchar(36) [ref: > event_organizer.id, not null]
    user_id varchar(36) [ref: > user.id, not null]
    indexes {
        (organizer_id, user_id) [pk]
    }
}

// EVENT
Table event_categories {
    id varchar(36) [pk, note: "UUID for category, primary key"]
    name varchar [not null]
    description text [default: null]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

Table category_event {
    category_id varchar(36) [ref: > event_categories.id, not null, note: "e.g. Music, Sport, ..."]
    event_id varchar(36) [ref: > event.id, not null]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
    indexes {
        (category_id, event_id) [pk]
    }
}

Table event_type {
    id varchar(36) [pk, note: "UUID for event type, primary key"]
    name varchar [not null]
    description text [default: null]
    default_icon_url varchar [default: null]
    default_image_url varchar [default: null]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

Table event {
    id varchar(36) [pk, note: "UUID for event, primary key"]
    organizer_id varchar(36) [ref: > event_organizer.id, not null]
    event_type_id varchar(36) [ref: > event_type.id, not null]
    title varchar [not null]
    description text [default: null]
    address_id varchar(36) [ref: > address.id, note: "reference of where the event will take place"]
    is_public boolean [default: true, note: "false if only the organizer can invite participants"]
    is_online boolean [note: "true or false"]
    is_paid boolean [default: true, note: "paid or free event"]
    total_capacity int [note: "maximum number of attendees"]
    sales_tickets_start_date timestamp [note: "e.g 17/08/25"]
    sales_tickets_end_date timestamp [note: "e.g 28/08/25"]
    online_url varchar(255) [default: null, note: "Will be defined only if the will de online"]
    min_age_attendee int [default: null]
    max_age_attendee int [default: null]
    gender_of_attendee enum("FEMALE", "MALE", "MALE_FEMALE") [default: "MALE_FEMALE"]
    start_datetime timestamp [not null, note: "First occurrence start, e.g 2024-08-01 09:00:00+01"]
    end_datetime timestamp [not null, note: "First occurrence end, e.g 2024-08-01 17:00:00+01"]
    duration_minutes int [not null, note: "Duration in minutes , e.g 45"]

    //RECURRING
    is_recurring boolean [default: false, note: "Whether the event repeats"]
    original_event_id varchar(36) [ref: > event.id, default: null, note: "reference of original event"]
    occurrence_number int [default: null]
    // END RECURRING

    validation_status enum("DRAFT", "PENDING_APPROVAL", "APPROVED", "REJECTED", "PUBLISHED", "CANCELLED") [default: "DRAFT"]
    is_active boolean [default: true, note: "to enable or disable an instance"]

    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
    indexes {
        (organizer_id, title) [unique]
    }
}

Table recurring_event {
    id varchar(36) [pk, note: "UUID for recurring event, primary key"]
    event_id varchar(36) [ref: > event.id, not null, note: "reference of event"]
    recurrence_pattern enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY') [default: null, note: "Recurrence frequency"]
    recurrence_end_condition enum('DATE', 'COUNT', '...') [default: 'DATE', note: "How recurrence ends, e.g DATE"]
    recurrence_end_date date [default: null, note: "Last possible occurrence date, e.g 2025-12-31"]
    recurrence_count int [default: null, note: "Max number of occurrences, e.g 12"]
    // recurrence_interval int [default: 1, note: "Interval between recurrences, e.g 2 (bi-weekly)"]
    recurrence_byday varchar(60) [default: null, note: "Days of week, e.g MONDAY,WEDNESDAY,FRIDAY"]
    recurrence_bymonthday varchar(60) [default: null, note: "Days of month (e.g., 15 for 15th). 1,15"]
    // recurrence_byyearday varchar(60) [default: null, note: "Days of year (1-366), e.g. 32,120,243"]
    recurrence_byyearmonth varchar(60) [default: null, note: "Months of year (JANUARY-DECEMBER), e.g APRIL,MARCH,JULY,..."]
    recurrence_byyearmonthday varchar(60) [default: null, note: "Days of month (e.g., 15 for 15th). 1,15"]
    recurrence_timezone varchar(60) [default: "GMT+1", note: "Timezone for recurrence, e.g. Africa/Douala"]
}

Table sponsor {
    id varchar(36) [pk, note: "Unique identifier for the sponsor"]
    organizer_id varchar(36) [ref: > event_organizer.id, not null]
    organization_name varchar(255) [not null, note: "Legal name of sponsoring organizationm, e.g TechCorp Inc."]
    display_name varchar(255) [note: "Public-facing name (if different), e.g TechCorp"]
    logo_url varchar(512) [note: "HTTPS URL to high-res logo, e.g https://cdn.example.com/logos/techcorp.png"]
    website_url varchar(512) [note: "Sponsor's website, e.g https://techcorp.com"]
    contact_name varchar(255) [not null, note: "Main point of contact, e.g John Smith"]
    contact_email varchar(255) [not null, note: "Contact email, e.g john.smith@techcorp.com"]
    contact_phone varchar(20) [note: "Contact phone (E.164 format), e.g +12025551234"]
    is_active boolean [default: true, note: "to enable or disable an instance"]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

Table sponsored_event {
    event_id varchar(36) [ref: > event.id, not null, note: "reference of event sponsored"]
    sponsor_id varchar(36) [ref: > sponsor.id, not null, note: "reference of sponsor"]
    indexes {
        (event_id, sponsor_id) [unique]
    }
}

Table event_validation_status {
    id varchar(36) [pk, note: "UUID for event validation, primary key"]
    event_id varchar(36) [ref: > event.id, not null, note: "reference of event"]
    event_status enum("DRAFT", "PENDING_APPROVAL", "APPROVED", "REJECTED", "PUBLISHED", "CANCELLED") [default: "DRAFT"]
    validate_notes text [default: null, note: "comment of the user approved the event"]
    validate_by varchar(36) [ref: > user.id, not null, note: "reference of user who make validation"]
    validate_at timestamp [default: `now()`]
    indexes {
        (event_id, event_status) [unique]
    }
}

Table event_image {
    id varchar(36) [pk, note: "UUID for image, primary key"]
    event_id varchar(36) [ref: > event.id, not null, note: "reference of event"]
    image_url varchar(255) [not null]
    is_primary boolean [default: false, note: "true if it is the preview image for the event"]
    caption varchar(255) [default: null, note: "title or brief explanation accompanying the image or illustration"]
    upload_at timestamp [default: `now()`, note: "when it goes online"]
    indexes {
        (event_id, image_url) [unique]
    }
}

Table event_tag {
    id varchar(36) [pk, note: "UUID for tag, primary key"]
    name varchar(60) [not null, unique, note: "limited tickets, ..."]
    description text [default: null]
    created_at timestamp [default: `now()`]
}

Table event_tag_mapping {
    event_id varchar(36) [ref: > event.id, not null, note: "reference of event"]
    tag_id varchar(36) [ref: > event_tag.id, not null, note: "reference of event tag"]
    indexes {
        (event_id, tag_id) [unique]
    }
}

// TICKET
Table ticket_type {
    id varchar(36) [pk, note: "UUID for ticket type, primary key"]
    event_id varchar(36) [ref: > event.id, not null, note: "reference of event"]
    name varchar(60) [not null, note: "ticket name, e.g: VIP, ..."]
    description text
    price decimal(10, 2) [not null]
    quantity_available int [not null]
    number_of_attendee int [default: 1]
    sales_start_date timestamp [note: "e.g 17/08/25"]
    sales_end_date timestamp [note: "e.g 28/08/25"]
    min_per_order int [default: 1, note: "min number of the tickets user can book one time"]
    max_per_order int [default: null, note: "max number of the tickets user can book one time"]
    features json [null, note: "Ticket avantages, [{'prop1': 'valu1', 'prop2': 'value1', ...}]"]
    is_active boolean [default: true, note: "to enable or disable an instance"]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

// ATTENDEE
Table attendee {
    id varchar(36) [pk, note: "UUID for attendee type, primary key"]
    user_id varchar(36) [ref: > user.id, not null]
    email varchar(36)
    phone varchar
    first_name varchar
    last_name varchar
    special_needs text [note: "what the attendee likes (e.g Hobbies, interests, ...)"]
    is_active boolean [default: true, note: "to enable or disable an instance"]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

// EVENT BOOKMARK
Table event_bookmark {
    user_id varchar(36) [ref: > user.id, not null, note: "user who bookmarks the event"]
    event_id varchar(36) [ref: > event.id, not null, note: "event which had bookmarked by attendee"]
    indexes {
        (user_id, event_id) [pk]
    }
}

// EVENT LIKES
Table event_like {
    user_id varchar(36) [ref: > user.id, not null, note: "user who likes the event"]
    event_id varchar(36) [ref: > event.id, not null, note: "event which had liked by attendee"]
    indexes {
        (user_id, event_id) [pk]
    }
}

Table event_attendees {
    event_id varchar(36) [ref: > event.id, not null, note: "event which had liked by attendee"]
    attendee_id varchar(36) [ref: > attendee.id, not null, note: "person who will be present on the event"]
    is_active boolean [default: true, note: "to enable or disable an instance"]
    created_at timestamp [default: `now()`]
    indexes {
        (event_id, attendee_id) [pk]
    }
}

// ORDER
Table order {
    id varchar(36) [pk, note: "UUID for order, primary key"]
    user_id varchar(36) [ref: > user.id, not null, note: "the customer who places the order"]
    event_id varchar(36) [ref: > event.id, not null, note: "reference of event"]
    total_amount decimal(10, 2) [not null]
    payment_status enum("PENDING", "PAID", "FAILED") [default: "PENDING"]
    payment_method varchar [note: "OM, MOMO, ..."]
    payment_reference varchar
    amount_paid decimal(10, 2) [default: 0]
    payment_phone varchar
    beneficiary_phone varchar
    payment_reference_id varchar(255)
    is_active boolean [default: true, note: "to enable or disable an instance"]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

// Table order_item {
//     id varchar(36) [pk, note: "UUID for order item, primary key"]
//     order_id varchar(36) [ref: > order.id, not null]
//     ticket_type_id varchar(36) [ref: > ticket_type.id, not null]
//     quantity int [not null]
//     unit_price decimal(10, 2) [not null]
//     subtotal decimal(10, 2) [not null]
//     indexes {
//         (order_id, ticket_type_id) [unique]
//     }
// }

Table tickets {
    id varchar(36) [pk, note: "UUID for ticket, primary key"]
    order_id varchar(36) [ref: > order.id, not null]
    ticket_type_id varchar(36) [ref: > ticket_type.id, not null]
    price decimal(10, 2) [not null]
    attendee_id varchar(36) [ref: > attendee.id, note: "person who will be present on the event"]
    ticket_number varchar(20) [not null, unique, note: "e.g EventName/DayMonthYear/TicketNumberPerDay;  RR/170925/0085,  RR = Retro Revival or RERE if RR already exists. It's also unique per organizer"]
    qr_code_url varchar(255) [not null, unique, note: "unique per event"]
    status enum("VALID", "USED", "CANCELLED", "TRANSFERRED") [default: "VALID"]
    check_in_time timestamp [default: null]
    check_in_by varchar(36) [ref: > user.id, default: null, note: "user who validates the ticket"]
    is_active boolean [default: true, note: "to enable or disable an instance"]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

// EVENT FEEDBACK
Table event_feedback {
    event_id varchar(36) [ref: > event.id, not null, note: "event which had liked by attendee"]
    attendee_id varchar(36) [ref: > attendee.id, not null, note: "person who will be present on the event"]
    ticket_id varchar(36) [ref: > tickets.id, default: null, note: "reference of ticket"]
    rating enum(1, 2, 3, 4, 5) [default: null]
    feedback text [default: null, note: "appreciation of the attendee after participating to the event"]
    is_active boolean [default: true, note: "to enable or disable an instance"]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
    indexes {
        (event_id, attendee_id) [pk]
    }
}

Table feature_event {
    event_id varchar(36) [ref: > event.id, not null, note: "event reference"]
    priority int [note: "1, 7, ..."]
    saved_at timestamp [default: `now()`]
    update_at timestamp [default: null]
    indexes {
        (event_id) [pk]
    }
}

Table popular_event {
    event_id varchar(36) [ref: > event.id, not null, note: "event reference"]
    participation int [not null, note: "number of attendees"]
    bookmarked int [not null, note: "number of bookmark"]
    liked int [not null, note: "number of likes"]
    saved_at timestamp [default: `now()`]
    update_at timestamp [default: null]
    indexes {
        (event_id) [pk]
    }
}

Table sponsor_event {
    event_id varchar(36) [ref: > event.id, not null, note: "event reference"]
    sponsors int [not null, note: "number of sponsor"]
    saved_at timestamp [default: `now()`]
    update_at timestamp [default: null]
    indexes {
        (event_id) [pk]
    }
}

// ---
// Notifications
// ---
Table notification_type {
  id varchar(36) [pk, note: "UUID for the notification type, primary key"]
  name varchar [not null, note: "POS Created, POS Validated, ..."]
  message text [not null, note: "message content"]
  description text
  created_at timestamp [default: `now()`, not null, note: "Timestamp of user creation"]
  updated_at timestamp [default: null, note: "Timestamp of last user update"]
}

Table notification_template {
  id varchar(36) [pk, note: "UUID for the notification type, primary key"]
  name varchar [not null, note: "Event Created, Event Validated, ..."]
  template text [not null, note: "message content"]
  description text
  created_at timestamp [default: `now()`, not null, note: "Timestamp of user creation"]
  updated_at timestamp [default: null, note: "Timestamp of last user update"]
}

Table notification {
  id varchar(36) [pk, note: "UUID for the notifications, primary key"]
  template_id varchar(36) [ref: > notification_template.id, not null, note: "reference of notification template"]
  receipient_id varchar(36) [ref: > user.id, not null, note: "reference of receipient"]
  message text [not null, note: "formatted text with variables"]
  status enum("Send, Received, Read") [not null, default: "Send"]
  created_at timestamp [default: `now()`, not null, note: "Timestamp of user creation"]
}

//***
// Providers Marketplace
//***
Table provider_category {
    id varchar(36) [pk, note: "UUID for provider category, primary key"]
    name varchar(100) [not null]
    description text
    parent_category_id varchar(36) [ref: > provider_category.id, default: null, note: "reference of parent category"]
    is_active boolean [default: true, note: "to enable or disable an instance"]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

Table provider {
    id varchar(36) [pk, note: "UUID for provider, primary key"]
    user_id int [ref: > user.id, not null]

    // provider properties
    business_name varchar(255) [not null]
    banner_image_url varchar(255)
    business_description text
    business_email varchar(100)
    business_phone varchar(20)
    business_website_url varchar(255)
    business_logo_url varchar(255)
    introduction_video_url varchar(255)
    experience_years int
    team_size int
    about text [note: "bio"]
    address_id varchar(36) [ref: > address.id]

    // provider validation
    status enum('pending', 'approved', 'rejected', 'suspended') [default: 'pending']
    validate_notes text
    validate_by varchar(36) [ref: > user.id, default: null]
    validate_at timestamp
    is_active boolean [default: true, note: "to enable or disable an instance"]

    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

Table provider_category_mapping {
    provider_id varchar(36) [ref: > provider.id, not null]
    category_id varchar(36) [ref: > provider_category.id, not null]
    indexes {
        (provider_id, category_id) [pk]
    }
}

Table provider_service {
    id varchar(36) [pk, note: "UUID for provider service, primary key"]
    provider_id varchar(36) [ref: > provider.id, not null]
    event_type_id varchar(36) [ref: > event_type.id, not null]
    service_name varchar(255) [not null]
    about text [note: "Bio"]
    introduction_video_url varchar(255)
    base_price decimal(10, 2)
    indexes {
        (provider_id, event_type_id) [unique]
    }
}

//***
// Event Toolbox
//***
Table event_team {
    id varchar(36) [pk, note: "UUID for team, primary key"]
    event_id varchar(36) [ref: > event.id, not null, note: "event reference"]
    event_name varchar(255) [not null]
    description text
    created_by varchar(36) [ref: > user.id, not null, note: "user who create the team"]
    is_active boolean [default: true, note: "to enable or disable an instance"]
    created_at timestamp [default: `now()`]
    update_at timestamp [default: null]
}

Table team_member {
    id varchar(36) [pk, note: "UUID for team member, primary key"]
    event_team_id varchar(36) [ref: > event_team.id, not null]
    user_id varchar(36) [ref: > user.id, not null]
    role varchar(36)
    is_active boolean [default: true, note: "to enable or disable an instance"]
    join_date timestamp [default: `now()`]
    update_at timestamp [default: null]
}